return {
  version = "1.5",
  luaversion = "5.1",
  tiledversion = "2021.03.23",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 108,
  height = 64,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 59,
  nextobjectid = 1988,
  properties = {},
  tilesets = {
    {
      name = "images",
      firstgid = 1,
      tilewidth = 0,
      tileheight = 0,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 0,
      tiles = {}
    },
    {
      name = "block_out",
      firstgid = 1,
      tilewidth = 1920,
      tileheight = 1259,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 1,
      tiles = {
        {
          id = 5,
          image = "../../../../../../../../Z_DATAS/GFX/pexels/abstract/1920/pexels-steve-johnson-1292241.jpg",
          width = 1920,
          height = 1259
        }
      }
    }
  },
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 27,
      name = "block_out",
      visible = true,
      opacity = 0.59,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1961,
          name = "",
          type = "",
          shape = "rectangle",
          x = -192,
          y = 1120,
          width = 1920,
          height = 1259,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 10,
      name = "test",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "group",
      id = 36,
      name = "IMAGES",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 21,
          name = "static_images",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 26,
          name = "fg_images_deco",
          visible = true,
          opacity = 0.63,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 25,
          name = "bg_images_deco",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        }
      }
    },
    {
      type = "group",
      id = 35,
      name = "FGs",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 48,
          name = "fg2_deco_frontB",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 1986,
              name = "",
              type = "",
              shape = "rectangle",
              x = 616,
              y = 500,
              width = 92,
              height = 232,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 47,
          name = "fg2_deco_frontA",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 1985,
              name = "",
              type = "",
              shape = "rectangle",
              x = 564,
              y = 444,
              width = 192,
              height = 252,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 45,
          name = "fg2_deco_base",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 1984,
              name = "",
              type = "",
              shape = "rectangle",
              x = 436,
              y = 376,
              width = 432,
              height = 228,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 46,
          name = "fg2_deco_backA",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 1983,
              name = "",
              type = "",
              shape = "rectangle",
              x = 384,
              y = 316,
              width = 520,
              height = 308,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 49,
          name = "fg2_deco_backB",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 1982,
              name = "",
              type = "",
              shape = "rectangle",
              x = 320,
              y = 268,
              width = 624,
              height = 400,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 54,
          name = "fg1_deco_frontB",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 1981,
              name = "",
              type = "",
              shape = "rectangle",
              x = 1080,
              y = 756,
              width = 68,
              height = 268,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 37,
          name = "fg1_deco_frontA",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 1980,
              name = "",
              type = "",
              shape = "rectangle",
              x = 1124,
              y = 728,
              width = 108,
              height = 296,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 28,
          name = "fg1_deco_base",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 1979,
              name = "",
              type = "",
              shape = "rectangle",
              x = 656,
              y = 880,
              width = 300,
              height = 104,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 31,
          name = "fg1_deco_backA",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 1978,
              name = "",
              type = "",
              shape = "rectangle",
              x = 620,
              y = 916,
              width = 368,
              height = 92,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 53,
          name = "fg1_deco_backB",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 1977,
              name = "",
              type = "",
              shape = "rectangle",
              x = 572,
              y = 948,
              width = 448,
              height = 76,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 13,
      name = "grounds",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 276,
          name = "",
          type = "",
          shape = "rectangle",
          x = -192,
          y = 1024,
          width = 1920,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 277,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = -192,
          y = 0,
          width = 192,
          height = 1024,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 278,
          name = "",
          type = "",
          shape = "rectangle",
          x = -192,
          y = -240,
          width = 1920,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 279,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 1536,
          y = 0,
          width = 192,
          height = 1024,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1963,
          name = "",
          type = "",
          shape = "rectangle",
          x = 468,
          y = 848,
          width = 640,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1970,
          name = "",
          type = "",
          shape = "rectangle",
          x = 148,
          y = 976,
          width = 289.669,
          height = 8,
          rotation = -17,
          visible = true,
          properties = {}
        },
        {
          id = 1971,
          name = "",
          type = "",
          shape = "rectangle",
          x = 148,
          y = 684,
          width = 289.669,
          height = 8,
          rotation = 17,
          visible = true,
          properties = {}
        },
        {
          id = 1972,
          name = "",
          type = "",
          shape = "rectangle",
          x = 316,
          y = 652,
          width = 289.669,
          height = 8,
          rotation = -17,
          visible = true,
          properties = {}
        },
        {
          id = 1973,
          name = "",
          type = "",
          shape = "rectangle",
          x = 124,
          y = 452,
          width = 289.669,
          height = 8,
          rotation = 17,
          visible = true,
          properties = {}
        },
        {
          id = 1974,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1164,
          y = 820,
          width = 289.669,
          height = 8,
          rotation = 25,
          visible = true,
          properties = {}
        },
        {
          id = 1975,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1232,
          y = 756,
          width = 289.669,
          height = 8,
          rotation = -25,
          visible = true,
          properties = {}
        },
        {
          id = 1976,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1036,
          y = 504,
          width = 289.669,
          height = 8,
          rotation = 25,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "group",
      id = 34,
      name = "BGs",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 56,
          name = "bg1_deco_frontB",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 38,
          name = "bg1_deco_frontA",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 30,
          name = "bg1_deco_base",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 29,
          name = "bg1_deco_backA",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 57,
          name = "bg1_deco_backB",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {}
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 44,
          name = "bg2_deco_frontB",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 1969,
              name = "",
              type = "",
              shape = "ellipse",
              x = 252,
              y = 920,
              width = 484,
              height = 88,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 41,
          name = "bg2_deco_frontA",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 1968,
              name = "",
              type = "",
              shape = "ellipse",
              x = 176,
              y = 864,
              width = 608,
              height = 172,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 42,
          name = "bg2_deco_base",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 1967,
              name = "",
              type = "",
              shape = "ellipse",
              x = 440,
              y = 756,
              width = 104,
              height = 188,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 40,
          name = "bg2_deco_backA",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 1966,
              name = "",
              type = "",
              shape = "ellipse",
              x = 384,
              y = 684,
              width = 216,
              height = 272,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 43,
          name = "bg2_deco_backB",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 1965,
              name = "",
              type = "",
              shape = "ellipse",
              x = 324,
              y = 608,
              width = 328,
              height = 368,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 33,
      name = "slides",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 52,
      name = "danger",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "sensors",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 18,
      name = "collectibles",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 17,
      name = "ladders",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 51,
      name = "doors",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 16,
      name = "ptpfs",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "mvpfs",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 58,
      name = "moveables",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 14,
      name = "playable",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1964,
          name = "player1",
          type = "",
          shape = "ellipse",
          x = 592,
          y = 764,
          width = 51,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
